PATCH http://localhost:3000/api/v1/users/67df24d7f644323f7a982ab6
Content-Type: application/json
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.uLUQKCAZ3c_a94nMsfDMCYLRNHdkET0xoLd-DVVj4Aw

{
  "role": "admin"
}


PATCH http://localhost:3000/api/v1/user/profile
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2IwMmVhZDY0ZTAwZGYzMDZmODlhMmUiLCJuYW1lIjoiSm9obiBEb2UiLCJyb2xlIjoidXNlciIsImlhdCI6MTUxNjIzOTAyMn0.7GcpfbZmqruPCRR61Ko19YS7wAsu-xwk-MIx3qUGjWM

{
   "phoneNumber": "0106603193",
    "email": "tetox@dxdoe.com"
}
