GET http://localhost:3000/api/v1/users/
?limit=10
&page=1&sort=desc&search=doe
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJyb2xlIjoiYWRtaW4ifQ.mwRIj6zCmVo5Zo5Ey__BkEiOszfshZdsBUHRJZEexfQ


GET http://localhost:3000/api/v1/users/67ad8f4f2f0b5662151b1d70
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJyb2xlIjoiYWRtaW4ifQ.mwRIj6zCmVo5Zo5Ey__BkEiOszfshZdsBUHRJZEexfQ



GET http://localhost:3000/api/v1/user/profile
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTZiN2UzYWQxMTk4NzYyYWE5ZTU4ZCIsIm5hbWUiOiJsb2xhIGdhcmNpYSIsImVtYWlsIjoibG9sYTYwMDcxQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiYWdlIjoyOCwiZ2VuZGVyIjoibWFsZSIsInBhc3N3b3JkUmVzZXRFeHBpcmVzIjpudWxsLCJ2ZXJpZmljYXRpb25Db2RlIjpudWxsLCJpYXQiOjE3NDMyODI5NTAsImV4cCI6MTc0MzI4NjU1MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.7-hR6MdRXlofJLgiqOip4ikjHr7HLO84suN1yx1BkN4
