
PATCH http://localhost:3000/api/v1/order/60d21b4667d0d8992e610c85/cash-completed
Content-Type: application/json
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.uLUQKCAZ3c_a94nMsfDMCYLRNHdkET0xoLd-DVVj4Aw
lang: ar


PATCH http://localhost:3000/api/v1/order/60d21b4667d0d8992e610c85/delivered
Content-Type: application/json
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.uLUQKCAZ3c_a94nMsfDMCYLRNHdkET0xoLd-DVVj4Aw
lang: ar



